import { db } from '@/lib/db'
import type { Resource } from '@/types'

const SEED_RESOURCES: Omit<Resource, 'id'>[] = [
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    type: 'book',
    summary: 'Small changes compound into remarkable results. Systems over goals.',
    keyPrinciples: ['1% better every day', 'Identity-based habits', 'Environment design', 'Habit stacking'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Designing Your Life',
    author: 'Bill Burnett & Dave Evans',
    type: 'book',
    summary: 'Apply design thinking to build a meaningful life. Prototype before committing.',
    keyPrinciples: ['Life View + Work View', 'Odyssey plans', 'Bias to action', 'Reframe problems'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'The Almanack of Naval Ravikant',
    author: 'Eric Jorgenson',
    type: 'book',
    summary: 'Wealth creation through leverage and specific knowledge. Happiness is a skill.',
    keyPrinciples: ['Specific knowledge', 'Leverage', 'Judgment over effort', 'Desire is suffering'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Meditations',
    author: 'Marcus Aurelius',
    type: 'book',
    summary: 'Stoic philosophy for daily practice. Control what you can, accept what you cannot.',
    keyPrinciples: ['Amor fati', 'Memento mori', 'The dichotomy of control', 'Virtue as the sole good'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    type: 'book',
    summary: 'Focused work in a distracted world. Depth over busyness.',
    keyPrinciples: ['Monastic vs bimodal schedules', 'Drain the shallows', 'Productive meditation', 'Embrace boredom'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'The 4-Hour Body',
    author: 'Tim Ferriss',
    type: 'book',
    summary: 'Minimum effective dose for physical performance. Data-driven health optimization.',
    keyPrinciples: ['Minimum effective dose', 'Slow-carb diet', 'Sleep optimization', 'Body composition > weight'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Principles',
    author: 'Ray Dalio',
    type: 'book',
    summary: 'Radical transparency and systematic decision-making for life and work.',
    keyPrinciples: ['Pain + Reflection = Progress', 'Radical transparency', 'Believability-weighted decisions', 'Embrace reality'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'The War of Art',
    author: 'Steven Pressfield',
    type: 'book',
    summary: 'Defeating resistance. Turning pro means showing up every day regardless of how you feel.',
    keyPrinciples: ['Resistance is universal', 'Turn pro', 'Do the work', 'The muse rewards discipline'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Man\'s Search for Meaning',
    author: 'Viktor Frankl',
    type: 'book',
    summary: 'Purpose survives any suffering. You always have the freedom to choose your attitude.',
    keyPrinciples: ['Logotherapy', 'Meaning through suffering', 'Freedom of attitude', 'Responsibility to life'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Essentialism',
    author: 'Greg McKeown',
    type: 'book',
    summary: 'Less but better. The disciplined pursuit of less.',
    keyPrinciples: ['Trade-offs are real', 'Hell yes or no', 'Protect the asset', 'Routine enables creativity'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    type: 'book',
    summary: 'Two systems of thought. Understanding cognitive biases for better decisions.',
    keyPrinciples: ['System 1 vs System 2', 'Loss aversion', 'Anchoring', 'Planning fallacy'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    type: 'book',
    summary: 'Wealth is what you don\'t spend. Behavior matters more than intelligence in finance.',
    keyPrinciples: ['Compounding', 'Tail events drive outcomes', 'Reasonable > Rational', 'Room for error'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Why We Sleep',
    author: 'Matthew Walker',
    type: 'book',
    summary: 'Sleep is the foundation of all performance. 8 hours is non-negotiable.',
    keyPrinciples: ['Sleep debt is real', 'REM for emotional regulation', 'Circadian rhythm', 'No catch-up sleep'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'The Compound Effect',
    author: 'Darren Hardy',
    type: 'book',
    summary: 'Small, consistent actions create massive results over time.',
    keyPrinciples: ['Choices compound', 'Momentum', 'Influences matter', 'Acceleration through consistency'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
  {
    title: 'Can\'t Hurt Me',
    author: 'David Goggins',
    type: 'book',
    summary: 'You are capable of far more than you think. Embrace discomfort.',
    keyPrinciples: ['The 40% rule', 'Accountability mirror', 'Callusing the mind', 'The cookie jar'],
    relevantPillarIds: [],
    unlockedAt: null,
  },
]

export async function seedResources(): Promise<void> {
  const count = await db.resources.count()
  if (count > 0) return

  await db.resources.bulkAdd(SEED_RESOURCES as Resource[])
}
